apiVersion: apps/v1
kind: Deployment
metadata:
    name: uda-capstone
    labels:
        app: uda-capstone
    namespace: default
spec:
    selector:
        matchLabels:
            app: uda-capstone
    replicas: 5
    strategy:
        rollingUpdate:
            maxSurge: 35%
            maxUnavailable: 35%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: uda-capstone
        spec:
            containers:
                - image: ejstylz/uda-capstone
                  imagePullPolicy: Always
                  name: uda-capstone
                  ports:
                      - containerPort: 8080
