apiVersion: v1
kind: Service
metadata:
    name: uda-capstone
    labels:
        app: uda-capstone
    namespace: default
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    selector:
        app: uda-capstone
